<?php 
$_library_response = <<<'JSON'
{
  "library": {
      "catalog_url": "http://nypl.bibliocommons.com",
      "id": "nypl",
      "name": "New York Public Library"
  }
}
JSON;

$_locations_response = <<<'JSON'
{
    "locations": [
        {
            "id": "52-HU",
            "name": "115th Street"
        },
        {
            "id": "52-HD",
            "name": "125th Street"
        },
        {
            "id": "52-FE",
            "name": "58th Street"
        },
        {
            "id": "52-SS",
            "name": "67th Street"
        }
    ]
}
JSON;
